### PR TITLE
Added failure percentage and test to exported data

### PR DESCRIPTION
**Pull request by 0xfede7c8**

### CODE REVIEW

**Comment by hughsie** [comment]
Ci needs to pass :)

    NameError: name 'json' is not defined

**Comment by 0xfede7c8** [comment]
I'm unussually sloppy today.

**Comment by 0xfede7c8** [comment]
Oh, so we have to be pylint compliant. Good to know.

**Comment by hughsie** [comment]
Now, if you `git rebase master -i` and change all those other commits to fixups, then force push the branch to update this PR, you'll look perfect :)

**Comment by 0xfede7c8** [comment]
Doesn't Github already has an squash and merge option? I think it would be the same result you are looking without the force part.

**Comment by hughsie** [comment]
> Github already has an squash and merge option

**Comment by hughsie** [comment]
> Github already has an squash and merge option

It does, but we've disabled it for this repo. It's too easy to accidentally *not* squash and accidentally have a ton of "fixup", "moar fixup" commits in master that live forever. If you squash locally and force push the PR will update and we can merge this.

**Comment by 0xfede7c8** [comment]
I already squashed it.

**Pull request merged**
