### PR TITLE
Wip/hughsie/become

### PR DESCRIPTION
**Pull request by hughsie**
This is a powerful admin-only action that allows me to verify bugs on the production instance. Or rather to verify that the user reporting the bug can actually see the buttons on the screen :)

### CODE REVIEW

**Comment by superm1** [comment]
As an alternative why not just sync to testing interface and reset the user password in the testing instance database?

**Comment by hughsie** [comment]
> As an alternative why not just sync to testing interface and reset the user password in the testing instance database?

Yes, this is what I was doing before, but syncing the prod->testing databases was becoming more of a pain. If you think this is a Bad Idea (tm) I can drop this, or perhaps make it conditional on DEBUG=1 being set.

**Comment by superm1** [comment]
> Yes, this is what I was doing before, but syncing the prod->testing databases was becoming more of a pain. If you think this is a Bad Idea (tm) I can drop this, or perhaps make it conditional on DEBUG=1 being set.

I do think it's a bad idea, it opens up the opportunity for falsified event logs in the event admin credentials were hacked.  I know there are more dangerous things that can be done as admin, but stealthy stuff is scary.

I would think you're better off making it easier to sync DB to testing/staging.

**Comment by hughsie** [comment]
> I do think it's a bad idea

Fair enough, thanks for the sanity check.

**Pull request closed without merging**
