### PR TITLE
Wip/hughsie/race

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Review by superm1 — APPROVED** [review]
`regenerate_ts` is a poor man's mutex 👍

**Comment by joakim-tjernlund** [comment]
Now I just got:
```
fwupdtool refresh
Loading…                 [***************************************]
15:06:33:0072 Fwupd                fwupd_remote_get_metadata_uri_sig: assertion 'FWUPD_IS_REMOTE (self)' failed
no metadata signature URI available
```
Do I need to do something on my side?

**Comment by hughsie** [comment]
> no metadata signature URI available

Can you attach your files in /etc/fwupd/remotes.d please?

**Comment by hughsie** [comment]
> fwupdtool refresh

Gahh, that was supposed to be `fwupdmgr refresh` sorry. `fwupdtool` is supposed to work too, but that's not what we're fixing here.

**Comment by superm1** [comment]
> > fwupdtool refresh
> 
> Gahh, that was supposed to be `fwupdmgr refresh` sorry. `fwupdtool` is supposed to work too, but that's not what we're fixing here.

I think it's some memory corruption happening when calling `fu_util_download_out_of_process` where the first argument is actually modified somewhere down that chain.  It seems to happen consistently on the 3rd time `fu_common_spawn_sync` is called when the main loop runs (line 733).  You can see that `argv[1]` is destroyed in this case.

It only runs 3 times if 2 remotes are enabled, hence why it happens when lvfs-testing gets turned on.

**Comment by joakim-tjernlund** [comment]
> > > fwupdtool refresh
> > 
> > 
> > Gahh, that was supposed to be `fwupdmgr refresh` sorry. `fwupdtool` is supposed to work too, but that's not what we're fixing here.
> 
> I think it's some memory corruption happening when calling `fu_util_download_out_of_process` where the first argument is actually modified somewhere down that chain. It seems to happen consistently on the 3rd time `fu_common_spawn_sync` is called when the main loop runs (line 733). You can see that `argv[1]` is destroyed in this case.
> 
> It only runs 3 times if 2 remotes are enabled, hence why it happens when lvfs-testing gets turned on.

I see, if you are about to fix that too I will leave my fwupd alone until it is fixed and try again

**Comment by hughsie** [comment]
> some memory corruption happening

I have a fix give me 30 mins

**Comment by hughsie** [comment]
> some memory corruption happening

https://github.com/fwupd/fwupd/pull/2368

**Comment by joakim-tjernlund** [comment]
> > some memory corruption happening
> 
> [fwupd/fwupd#2368](https://github.com/fwupd/fwupd/pull/2368)

```
fwupdtool refresh
Loading…                 [***************************************]
```
Looks better :) Thanks

**Pull request merged**
