### PR TITLE
Added atom-feed to devices.

### PR DESCRIPTION
**Pull request by bjoern-tantau**
See  #447.
This is untested but should work mostly.

Only the dates should be converted from `2019-05-23 01:08:28` to `2019-05-23T01:08:28Z`. I don't know how to properly do that with python.

### CODE REVIEW

**Comment by hughsie** [comment]
> Only the dates should be converted

I think you want to append `.isoformat()` to do that. It's looking great already!

**Comment by bjoern-tantau** [comment]
I added the `.isoformat()` but I couldn't get the website up on my Ubuntu environment. So this is completely untested. But even if the timestamps are not completely correct I suspect that most clients will be able to handle several different timestamp formats.

**Comment by hughsie** [comment]
> but I couldn't get the website up on my Ubuntu environment

Where did you get stuck? I'm happy to help. We probably ought to test this in the self tests too.

**Comment by hughsie** [comment]
Replaced with https://github.com/fwupd/lvfs-website/pull/460 -- thanks.

**Pull request closed without merging**
