### PR TITLE
Allow researchers to run YARA queries on the public firmware

### PR DESCRIPTION
**Pull request by hughsie**
Some security researchers want to run YARA queries on the firmware on the LVFS.
They can (and do) this already, but it means:

 * Downloading tens of gigabytes of firmware using PULP_MANIFEST
 * Exploding each cabinet to get the capsule
 * Exploding each capsule into EFI binaries with chipsec
 * Running yara on the command line

Given the LVFS already has the shards cached for each firmware, just allow
authenticated users to run YARA queries on the public firmware. These are done
in an existing cron job as they typically take a few minutes to compile and run.

It's important to note that this functionality isn't providing anything more
than people can do already with wget and a shell script and so I don't think
it's overstepping the mark allowing carefully chosen security researchers
access to this kind of thing. If anything, I can keep an eye on them this way :)

### CODE REVIEW

**Comment by hughsie** [comment]
Screenshot from 2019-10-15 15-57-33

**Comment by superm1** [comment]
> It's important to note that this functionality isn't providing anything more
than people can do already with wget and a shell script and so I don't think
it's overstepping the mark allowing carefully chosen security researchers
access to this kind of thing. If anything, I can keep an eye on them this way :)

I think the important comparison to draw between someone `wget`/`bash` scripting and using a logged in instance is that the security boundaries to OEM embargo channels become a lot more blurry.  A small bug that uncovers an OEM's firmware to another logged in OEM is certainly bad, but uncovering it to a security researcher goes from bad to a lot worse potentially.

**Comment by hughsie** [comment]
> security boundaries to OEM embargo channels become a lot more blurry

Agreed -- this is explicitly only scanning stuff in `stable` -- even `testing` is filtered out.

**Comment by superm1** [comment]
Considering this is for researchers does it even make sense to render a UX as the result?  I wonder if a CSV is better suited for their needs.

**Comment by hughsie** [comment]
I think a CSV export is a good idea, but I don't think it's the only thing they need.

**Pull request merged**
