### PR TITLE
Allow adding component claims based on the hash of a shard

### PR DESCRIPTION
**Pull request by hughsie**
This allows us to add negative security claims to components that contain shards
with known security problems, for instance older versions of UsbRt.

### CODE REVIEW

**Comment by hughsie** [comment]
Screenshot_2020-01-24 LVFS Component Shard Claims
Screenshot_2020-01-24 LVFS Component Shard Checksums
Screenshot_2020-01-24 LVFS Component Shard Components
Screenshot_2020-01-24 LVFS Component Shard Details

**Comment by superm1** [comment]
Correlating what is in one vendors image versus another brings up (what I think is) a good idea.  How about uploading some "reference" Tiano Core/OVMF images from the recent git tags to LVFS and comparing to those?  You can then tell exactly what has changed from the different EDK II releases.
I guess technically you  can probably also add links to actual code when you know it hasn't changed.

**Comment by hughsie** [comment]
> uploading some "reference" Tiano Core/OVMF images

That's a good idea. I'll talk to Brian and see if we can get something more automated.

**Comment by superm1** [comment]
I'm curious are you seeing hashes the same across vendors?  I wonder if EDK hardcodes compiler and flags enough for reproducible builds type stuff to work.

**Comment by hughsie** [comment]
> I'm curious are you seeing hashes the same across vendors?

Ya, for things like Shell.efi a lot of vendors just use the Intel reference version.

**Comment by hughsie** [comment]
> nothing stands out to me

Other than the complete lack of tests :) I've added some now, nothing problematic found.

**Pull request merged**
