### PR TITLE
Fix all CSRF issues

### PR DESCRIPTION
**Pull request by hughsie**
Spotted by Justin Steven <justin@justinsteven.com>, many thanks.

### CODE REVIEW

**Comment by hughsie** [comment]
This adds quite a few UI issues (hence the draft...) but should work. I'll fix up the layout issues when I've read up a bit more on how to do the autolayout of multiple form elements in bootstrap.

**Comment by justinsteven** [comment]
Lots of grunt work needed in fixing this one. Thanks @hughsie!

**Comment by superm1** [comment]
@justinsteven you've been on fire with all the stuff you've found, color me quite impressed and happy :)

**Comment by justinsteven** [comment]
@superm1 I'm happy to help! :grin:

**Pull request merged**
