### PR TITLE
Allow the blocklist plugin to add persistent claims

### PR DESCRIPTION
**Pull request by hughsie**
This could be used for instance to detect Computrace, BootGuard or BIOSguard,
and used to provide helpful user information to the device model.

### CODE REVIEW

**Comment by hughsie** [comment]
Screenshot_2019-10-24 LVFS OptiPlex 3050 AIO

**Comment by superm1** [comment]
Lgtm

**Comment by hughsie** [comment]
@superm1 anything else you can think it makes sense to detect and display? I did wonder about BIOSGuard, but @out0xb2 pointed out you can have the DXEs but are not active on a particular CPU generation... Perhaps it makes sense to allow the vendors to "opt in" in the metainfo file for a "manual" claim?

**Comment by superm1** [comment]
I don't think making manual claims in metadata is valuable. There is nothing to stop lying (intentionally or unintentionally).

I do think that things like this can be informative claims but shouldn't be a positive or negative badge.

BootGuard makes great sense to me.

It's do agree that FV don't always get activated so this claim can't be part of a security story, just informative that the firmware contains a security technology.

**Comment by hughsie** [comment]
Do you mean that manually added attributes like BootGuard are okay, OR that we should just show a BootGuard info claim if the firmware has the BG DXE?

**Comment by superm1** [comment]
Sorry if I was unclear.  I don't think manually added attributes are good for this.  These types of claims should only be made if there is some sort of evidence to support the claim (IE tearing apart a FV or ME image).

**Pull request merged**
